name: Java Playwright CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Java 17
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3. Setup Node.js 18 for Playwright
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 4. Install Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install

      # 5. Maven build
      - name: Maven build
        run: mvn clean install

      # 6. Run tests
      - name: Run tests
        run: mvn test
        continue-on-error: true  # чтобы workflow не падал при падении тестов

      # 7. Save Allure results as artifact
      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      # 8. Save screenshots as artifact
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/**

      # 9. Install Allure CLI
      - name: Install Allure CLI
        run: |
          sudo apt-add-repository ppa:qameta/allure -y
          sudo apt update
          sudo apt install allure -y

      # 10. Generate HTML report from allure-results
      - name: Generate Allure HTML report
        run: |
          allure generate target/allure-results -o allure-report --clean
          ls -R allure-report

      # 11. Deploy Allure report to GitHub Pages
      - name: Deploy Allure Report
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: allure-report
          force_orphan: true
