name: Java Playwright CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup JDK
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3. Setup Node.js for Playwright
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 4. Install Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install

      # 5. Maven build
      - name: Maven build
        run: mvn clean install

      # 6. Run tests
      - name: Run tests
        run: mvn test
        continue-on-error: true  # workflow не падает если тесты упали

      # 7. Save Allure results as artifact
      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      # 8. Save screenshots as artifact
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/**

      # 9. Generate Allure Report
      - name: Generate Allure Report
        run: mvn allure:report

      # 10. Copy Allure report to root folder for deploy
      - name: Prepare report for deploy
        run: |
          rm -rf allure-report
          cp -r target/site/allure-maven-plugin allure-report

      # 11. Deploy Allure Report to GitHub Pages
      - name: Deploy Allure Report
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: allure-report
          force_orphan: true
